### ISSUE TITLE
Error 500 (Internal Server Error) on Instagram Reels

### ISSUE THREAD

**Issue by jerichosy** [jerichosy/yt-dlp_info-extractor-api#9]
Traceback:
```
2023-02-05T13:49:17.404975+00:00 app[web.1]: [Instagram] Extracting URL: https://www.instagram.com/reel/CoQOqJIj1YJ/
2023-02-05T13:49:17.405168+00:00 app[web.1]: [Instagram] CoQOqJIj1YJ: Setting up session
2023-02-05T13:49:17.463849+00:00 app[web.1]: [Instagram] CoQOqJIj1YJ: Downloading JSON metadata
2023-02-05T13:49:17.562229+00:00 app[web.1]: WARNING: [Instagram] CoQOqJIj1YJ: General metadata extraction failed (some metadata might be missing).
2023-02-05T13:49:17.562236+00:00 app[web.1]: [Instagram] CoQOqJIj1YJ: Downloading webpage
2023-02-05T13:49:17.960346+00:00 app[web.1]: WARNING: [Instagram] unable to extract shared data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2023-02-05T13:49:17.960379+00:00 app[web.1]: WARNING: [Instagram] Main webpage is locked behind the login page. Retrying with embed webpage (some metadata might be missing).
2023-02-05T13:49:17.960382+00:00 app[web.1]: [Instagram] CoQOqJIj1YJ: Downloading embed webpage
2023-02-05T13:49:18.325231+00:00 app[web.1]: WARNING: [Instagram] unable to extract additional data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2023-02-05T13:49:18.325507+00:00 app[web.1]: ERROR: [Instagram] CoQOqJIj1YJ: Requested content is not available, rate-limit reached or login required. Use --cookies, --cookies-from-browser, --username and --password, or --netrc (instagram) to provide account credentials
2023-02-05T13:49:18.325907+00:00 app[web.1]: INFO:     152.32.112.33:0 - "GET /extract?url=https%3A%2F%2Fwww.instagram.com%2Freel%2FCoQOqJIj1YJ%2F HTTP/1.1" 500 Internal Server Error
2023-02-05T13:49:18.326621+00:00 app[web.1]: ERROR:    Exception in ASGI application
2023-02-05T13:49:18.326622+00:00 app[web.1]: Traceback (most recent call last):
2023-02-05T13:49:18.326622+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1497, in wrapper
2023-02-05T13:49:18.326623+00:00 app[web.1]:     return func(self, *args, **kwargs)
2023-02-05T13:49:18.326623+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1573, in __extract_info
2023-02-05T13:49:18.326623+00:00 app[web.1]:     ie_result = ie.extract(url)
2023-02-05T13:49:18.326624+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 680, in extract
2023-02-05T13:49:18.326624+00:00 app[web.1]:     ie_result = self._real_extract(url)
2023-02-05T13:49:18.326632+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/yt_dlp/extractor/instagram.py", line 456, in _real_extract
2023-02-05T13:49:18.326633+00:00 app[web.1]:     self.raise_login_required('Requested content is not available, rate-limit reached or login required')
2023-02-05T13:49:18.326633+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1140, in raise_login_required
2023-02-05T13:49:18.326633+00:00 app[web.1]:     raise ExtractorError(msg, expected=True)
2023-02-05T13:49:18.326634+00:00 app[web.1]: yt_dlp.utils.ExtractorError: [Instagram] CoQOqJIj1YJ: Requested content is not available, rate-limit reached or login required. Use --cookies, --cookies-from-browser, --username and --password, or --netrc (instagram) to provide account credentials
2023-02-05T13:49:18.326634+00:00 app[web.1]: 
2023-02-05T13:49:18.326634+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2023-02-05T13:49:18.326634+00:00 app[web.1]: 
2023-02-05T13:49:18.326635+00:00 app[web.1]: Traceback (most recent call last):
2023-02-05T13:49:18.326635+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
2023-02-05T13:49:18.326635+00:00 app[web.1]:     result = await app(self.scope, self.receive, self.send)
2023-02-05T13:49:18.326644+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2023-02-05T13:49:18.326644+00:00 app[web.1]:     return await self.app(scope, receive, send)
2023-02-05T13:49:18.326644+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
2023-02-05T13:49:18.326644+00:00 app[web.1]:     await super().__call__(scope, receive, send)
2023-02-05T13:49:18.326645+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
2023-02-05T13:49:18.326645+00:00 app[web.1]:     await self.middleware_stack(scope, receive, send)
2023-02-05T13:49:18.326645+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
2023-02-05T13:49:18.326645+00:00 app[web.1]:     raise exc
2023-02-05T13:49:18.326646+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
2023-02-05T13:49:18.326646+00:00 app[web.1]:     await self.app(scope, receive, _send)
2023-02-05T13:49:18.326646+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
2023-02-05T13:49:18.326646+00:00 app[web.1]:     raise exc
2023-02-05T13:49:18.326646+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
2023-02-05T13:49:18.326647+00:00 app[web.1]:     await self.app(scope, receive, sender)
2023-02-05T13:49:18.326647+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2023-02-05T13:49:18.326647+00:00 app[web.1]:     raise e
2023-02-05T13:49:18.326647+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2023-02-05T13:49:18.326647+00:00 app[web.1]:     await self.app(scope, receive, send)
2023-02-05T13:49:18.326647+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
2023-02-05T13:49:18.326647+00:00 app[web.1]:     await route.handle(scope, receive, send)
2023-02-05T13:49:18.326648+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/starlette/routing.py", line 266, in handle
2023-02-05T13:49:18.326648+00:00 app[web.1]:     await self.app(scope, receive, send)
2023-02-05T13:49:18.326648+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
2023-02-05T13:49:18.326648+00:00 app[web.1]:     response = await func(request)
2023-02-05T13:49:18.326648+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/fastapi/routing.py", line 227, in app
2023-02-05T13:49:18.326648+00:00 app[web.1]:     raw_response = await run_endpoint_function(
2023-02-05T13:49:18.326649+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
2023-02-05T13:49:18.326649+00:00 app[web.1]:     return await run_in_threadpool(dependant.call, **values)
2023-02-05T13:49:18.326649+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
2023-02-05T13:49:18.326649+00:00 app[web.1]:     return await anyio.to_thread.run_sync(func, *args)
2023-02-05T13:49:18.326649+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
2023-02-05T13:49:18.326649+00:00 app[web.1]:     return await get_asynclib().run_sync_in_worker_thread(
2023-02-05T13:49:18.326649+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
2023-02-05T13:49:18.326650+00:00 app[web.1]:     return await future
2023-02-05T13:49:18.326650+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
2023-02-05T13:49:18.326650+00:00 app[web.1]:     result = context.run(func, *args)
2023-02-05T13:49:18.326653+00:00 app[web.1]:   File "/app/./main.py", line 14, in extract
2023-02-05T13:49:18.326653+00:00 app[web.1]:     info_dict = ydl.extract_info(url, download=False)
2023-02-05T13:49:18.326653+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1486, in extract_info
2023-02-05T13:49:18.326653+00:00 app[web.1]:     return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
2023-02-05T13:49:18.326653+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1515, in wrapper
2023-02-05T13:49:18.326654+00:00 app[web.1]:     self.report_error(str(e), e.format_traceback())
2023-02-05T13:49:18.326654+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1007, in report_error
2023-02-05T13:49:18.326654+00:00 app[web.1]:     self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
2023-02-05T13:49:18.326654+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 947, in trouble
2023-02-05T13:49:18.326654+00:00 app[web.1]:     raise DownloadError(message, exc_info)
2023-02-05T13:49:18.326654+00:00 app[web.1]: yt_dlp.utils.DownloadError: ERROR: [Instagram] CoQOqJIj1YJ: Requested content is not available, rate-limit reached or login required. Use --cookies, --cookies-from-browser, --username and --password, or --netrc (instagram) to provide account credentials
2023-02-05T13:49:18.327025+00:00 heroku[router]: at=info method=GET path="/extract?url=https%3A%2F%2Fwww.instagram.com%2Freel%2FCoQOqJIj1YJ%2F" host=aqueous-reef-11508.herokuapp.com request_id=b6f1211b-d9b3-421a-8949-afa7d6652cbe fwd="152.32.112.33" dyno=web.1 connect=0ms service=991ms status=500 bytes=193 protocol=https
```

**Comment by jerichosy** [comment]
This issue does not happen on the local machine.

**Comment by jerichosy** [comment]
Switched to local machine (either for the meantime or possibly permanent).
